### ISSUE TITLE
inconsistency in data

### ISSUE THREAD

**Issue by alxsmith** [lennon-thomas/Montserrat-Length-Data#1]
@lennon-thomas 
SEE:
https://github.com/lennon-thomas/Montserrat-Length-Data/commits/master/Montserrat_Species_Length_Composition_Data_June_2016_AS.xls

lines 326 - 334 species code LUTJVI (silk snapper) but common name was
entered as Mahogany Snapper
# 746bd95baaa57f6858df075c0e9e47ef1cc65185

**Comment by lennon-thomas** [comment]
Thanks for flagging this! I went back to the hard copies of data, and it is supposed to be Mahogany snapper. I uploaded a new version of the file with the species code corrected
